### ISSUE TITLE
GPT4 8k

### ISSUE THREAD

**Issue by javierpazo** [ngmisl/CSV-Agent-Q_n_A#1]
how can it be changed to use GPT4 8k so it gets more tokens?

**Comment by ngmisl** [comment]
I don't have access to gpt4 api yet, but check this

from langchain.llms import OpenAIChat
https://python.langchain.com/en/latest/modules/indexes/vectorstores/examples/deeplake.html?highlight=Openaichat#retrieval-question-answering

Basically need to change from openai to openaichat. Let me, know if it worked ✌️
